### ISSUE TITLE
Salvando dentro do Array Incorretamente

### ISSUE THREAD

**Issue by carolinamlinhares** [carolinamlinhares/tcc-steel#1]
Linha 264 do Arquivo scriptDS

 ` approved.push(perfis[i], vrd, mrdOut, ratioDSV, ratioDSM, ratiopDSV, ratiopDSM); // saves to a list of approved sections

Esta salvando cada uma dessas variareis em uma posição do array, mas gostaria que fosse salvo como um único objeto em uma posicao do array.

**Comment by jefersonla** [comment]
Essa é fácil de resolver pense o seguinte, qual a notação para escrita de vetores em javascript é uma lista de variaveis ou valores dentre '[' e ']', o mesmo vale para objetos com uma única adição, cada objeto precisa ser tratado como uma propriedade, ou seja tem que ser mapeado por um nome assim você precisa não só escrever essas variaveis dentro de um bloco que inicie com '{' e termine com '}' como também precisa mapear cada um desses valores, e.g.:

```js
{
  "perfil": perfis[i],
  "vrd": vrd,
  "mrdOut": mrdOut,
  "ratioDSV": ratioDSV,
  "ratioDSM": ratioDSM,
  "ratiopDSV": ratiopDSV,
  "ratiopDSM": ratiopDSM
}
```
Assim bastar modificar seu commando para:

```js
approved.push({
  "perfil": perfis[i],
  "vrd": vrd,
  "mrdOut": mrdOut,
  "ratioDSV": ratioDSV,
  "ratioDSM": ratioDSM,
  "ratiopDSV": ratiopDSV,
  "ratiopDSM": ratiopDSM
});
```
Que vai funcionar
