### ISSUE TITLE
Ordenar Array .sort()

### ISSUE THREAD

**Issue by carolinamlinhares** [carolinamlinhares/tcc-steel#2]
Acontece nas linhas 286, 292, 298, 304, 310  e 316

Estou tentando classificar os resultados dentro da lista de acordo com uma propriedade do objeto

 approved.sort(function (a, b) {return a.ratioDSV - b.ratioDSV});

Esta indicando erro de sintaxe.

**Comment by jefersonla** [comment]
Esse erro está relacionado com o erro #1 , como você estava adicionado as variaveis direto e não um objeto não tinha como você acessar a propriedade, já que você estava adicionado variaveis e não objetos, e como eu disse variaveis não tem mapeamento ao não ser que elas pertençam a um objeto, e.g. `x = 10; y = x; console.log(y.x); // ERRO! não existe propriedade de nome x em y`, porém `x = 10; y = { "x": x}; console.log(y.x);` está correto.

A solução para esses bugs está em #4 caso tenha feito outras modificações pode fechar o pull-request (para deletar esse branch) e fazer as modifcações como apontado em #1 e #3.
